apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: authentication
  name: authentication
spec:
  type: LoadBalancer
  ports:
  - name: "8091"
    port: 8091
    targetPort: 8091
  selector:
    io.kompose.service: authentication