apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: integration
  name: integration
spec:
  type: LoadBalancer
  ports:
  - name: "8094"
    port: 8094
    targetPort: 8094
  selector:
    io.kompose.service: integration