apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: ogedik/api-gateway:1.0.0
        imagePullPolicy: Always
        name: api-gateway
        env:
          - name: DISCOVERY_SERVER_HOST
            valueFrom:
              configMapKeyRef:
                key: DISCOVERY_SERVER_HOST
                name: scrumier-config
          - name: DISCOVERY_SERVER_PORT
            valueFrom:
              configMapKeyRef:
                key: DISCOVERY_SERVER_PORT
                name: scrumier-config

      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  type: LoadBalancer
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8090
  selector:
    app: api-gateway
