apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authentication
  name: authentication
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: authentication
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - image: ogedik/authentication:1.0.0
        imagePullPolicy: Always
        name: authentication
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                key: DATABASE_HOST
                name: scrumier-config
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: DATABASE_PASSWORD
                name: scrumier-secrets
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                key: DATABASE_PORT
                name: scrumier-config
          - name: DATABASE_USERNAME
            valueFrom:
              configMapKeyRef:
                key: DATABASE_USERNAME
                name: scrumier-config
          - name: DISCOVERY_SERVER_HOST
            valueFrom:
              configMapKeyRef:
                key: DISCOVERY_SERVER_HOST
                name: scrumier-config
          - name: DISCOVERY_SERVER_PORT
            valueFrom:
              configMapKeyRef:
                key: DISCOVERY_SERVER_PORT
                name: scrumier-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: authentication
  name: authentication
spec:
  type: LoadBalancer
  ports:
    - name: "8091"
      port: 8091
      targetPort: 8091
  selector:
    app: authentication