apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config
  name: config
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: config
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - image: ogedik/config:1.0.0
        imagePullPolicy: Always
        name: config
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                key: DATABASE_HOST
                name: scrumier-config
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: DATABASE_PASSWORD
                name: scrumier-secrets
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                key: DATABASE_PORT
                name: scrumier-config
          - name: DATABASE_USERNAME
            valueFrom:
              configMapKeyRef:
                key: DATABASE_USERNAME
                name: scrumier-config
          - name: DISCOVERY_SERVER_HOST
            valueFrom:
              configMapKeyRef:
                key: DISCOVERY_SERVER_HOST
                name: scrumier-config
          - name: DISCOVERY_SERVER_PORT
            valueFrom:
              configMapKeyRef:
                key: DISCOVERY_SERVER_PORT
                name: scrumier-config
        ports: #change
          - name: liveness-port
            containerPort: 8092
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 1024Mi
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: config
  name: config
spec:
  type: LoadBalancer
  ports:
    - name: "8092"
      port: 8092
      targetPort: 8092
  selector:
    app: config