apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: integration
  name: integration
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: integration
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: integration
    spec:
      containers:
      - image: ogedik/integration:1.0.0
        imagePullPolicy: Always
        name: integration
        env:
          - name: DISCOVERY_SERVER_HOST
            valueFrom:
              configMapKeyRef:
                key: DISCOVERY_SERVER_HOST
                name: scrumier-config
          - name: DISCOVERY_SERVER_PORT
            valueFrom:
              configMapKeyRef:
                key: DISCOVERY_SERVER_PORT
                name: scrumier-config
        ports: #change
          - name: liveness-port
            containerPort: 8094
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 1024Mi
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: integration
  name: integration
spec:
  type: NodePort
  ports:
    - name: "8094"
      port: 8094
      targetPort: 8094
  selector:
    app: integration