apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: integration
  name: integration
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: integration
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: integration
    spec:
      containers:
      - image: ogedik/integration:1.0.0
        imagePullPolicy: Always
        name: integration
        env:
          - name: DISCOVERY_SERVER_HOST
            valueFrom:
              configMapKeyRef:
                key: DISCOVERY_SERVER_HOST
                name: scrumier-config
          - name: DISCOVERY_SERVER_PORT
            valueFrom:
              configMapKeyRef:
                key: DISCOVERY_SERVER_PORT
                name: scrumier-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: integration
  name: integration
spec:
  type: LoadBalancer
  ports:
    - name: "8094"
      port: 8094
      targetPort: 8094
  selector:
    app: integration