apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: time-tracker
  name: time-tracker
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: time-tracker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: time-tracker
    spec:
      containers:
        - image: ogedik/time-tracker:1.0.0
          imagePullPolicy: Always
          name: discovery-server
          ports: #change
            - name: liveness-port
              containerPort: 8761
          readinessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: time-tracker
  name: time-tracker
spec:
  type: NodePort
  ports:
    - name: "8095"
      port: 8095
      targetPort: 8095
  selector:
    app: time-tracker