apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: config
  name: config
spec:
  type: LoadBalancer
  ports:
  - name: "8092"
    port: 8092
    targetPort: 8092
  selector:
    io.kompose.service: config